name: Test
on: [ push,pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3' ]
        typo3: [ '12', '13' ]
        exclude:
          - php: '8.1'
            typo3: '13'
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: imagick
      - name: Composer install
        run: composer require typo3/minimal="^${{ matrix.typo3 }}" --dev --optimize-autoloader --prefer-dist
      - name: Composer code-check
        run: composer code-check
      - name: Composer code-test
        run: composer code-test
